# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MyWindow_def.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1238, 776)
        MainWindow.setStyleSheet("background-color: rgb(220, 191, 191);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.PhotoFrame = QtWidgets.QLabel(self.centralwidget)
        self.PhotoFrame.setGeometry(QtCore.QRect(30, 150, 551, 531))
        self.PhotoFrame.setStyleSheet("gridline-color: rgb(0, 0, 0);")
        self.PhotoFrame.setText("")
        self.PhotoFrame.setObjectName("PhotoFrame")
        self.AddingPhoto = QtWidgets.QPushButton(self.centralwidget)
        self.AddingPhoto.setGeometry(QtCore.QRect(50, 70, 211, 51))
        self.AddingPhoto.setStyleSheet("font: 25 oblique 11pt \"Umpush\";\n"
"background-color: rgb(255, 255, 255);\n"
"font: 63 13pt \"URW Gothic\";")
        self.AddingPhoto.setObjectName("AddingPhoto")
        self.AddingPhoto_2 = QtWidgets.QPushButton(self.centralwidget)
        self.AddingPhoto_2.setGeometry(QtCore.QRect(900, 70, 211, 51))
        self.AddingPhoto_2.setStyleSheet("font: 25 oblique 11pt \"Umpush\";\n"
"background-color: rgb(255, 255, 255);\n"
"font: 63 13pt \"URW Gothic\";")
        self.AddingPhoto_2.setObjectName("AddingPhoto_2")
        self.PhotoFrame_2 = QtWidgets.QLabel(self.centralwidget)
        self.PhotoFrame_2.setGeometry(QtCore.QRect(610, 140, 551, 531))
        self.PhotoFrame_2.setStyleSheet("gridline-color: rgb(0, 0, 0);")
        self.PhotoFrame_2.setText("")
        self.PhotoFrame_2.setObjectName("PhotoFrame_2")
        self.XORButton = QtWidgets.QPushButton(self.centralwidget)
        self.XORButton.setGeometry(QtCore.QRect(480, 20, 231, 91))
        self.XORButton.setStyleSheet("font: 25 oblique 11pt \"Umpush\";\n"
"background-color: rgb(255, 255, 255);\n"
"font: 63 13pt \"URW Gothic\";")
        self.XORButton.setObjectName("XORButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1238, 22))
        self.menubar.setObjectName("menubar")
        self.Exit = QtWidgets.QMenu(self.menubar)
        self.Exit.setObjectName("Exit")
        MainWindow.setMenuBar(self.menubar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.Quit = QtWidgets.QAction(MainWindow)
        self.Quit.setObjectName("Quit")
        self.Exit.addAction(self.Quit)
        self.menubar.addAction(self.Exit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.AddingPhoto.setText(_translate("MainWindow", "Выбрать изображение"))
        self.AddingPhoto_2.setText(_translate("MainWindow", "Выбрать изображение"))
        self.XORButton.setText(_translate("MainWindow", "Выполнить XOR"))
        self.Exit.setTitle(_translate("MainWindow", "Выход"))
        self.action.setText(_translate("MainWindow", "Сокрыть текст"))
        self.action_2.setText(_translate("MainWindow", "Извлечь текст"))
        self.action_3.setText(_translate("MainWindow", "Очистить поля"))
        self.Quit.setText(_translate("MainWindow", "Выход"))
