# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MyWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1238, 776)
        MainWindow.setStyleSheet("background-color: rgb(220, 191, 191);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.HideButton = QtWidgets.QPushButton(self.centralwidget)
        self.HideButton.setGeometry(QtCore.QRect(480, 20, 151, 51))
        self.HideButton.setStyleSheet("font: 25 oblique 11pt \"Umpush\";\n"
"background-color: rgb(255, 255, 255);\n"
"font: 63 13pt \"URW Gothic\";")
        self.HideButton.setObjectName("HideButton")
        self.TextEntry = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.TextEntry.setGeometry(QtCore.QRect(20, 20, 431, 121))
        self.TextEntry.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 63 13pt \"URW Bookman\";\n"
"gridline-color: rgb(0, 0, 0);")
        self.TextEntry.setObjectName("TextEntry")
        self.ExtractButton = QtWidgets.QPushButton(self.centralwidget)
        self.ExtractButton.setGeometry(QtCore.QRect(600, 90, 151, 51))
        self.ExtractButton.setStyleSheet("font: 25 oblique 11pt \"Umpush\";\n"
"background-color: rgb(255, 255, 255);\n"
"font: 63 13pt \"URW Gothic\";")
        self.ExtractButton.setObjectName("ExtractButton")
        self.PhotoFrame = QtWidgets.QLabel(self.centralwidget)
        self.PhotoFrame.setGeometry(QtCore.QRect(20, 210, 711, 511))
        self.PhotoFrame.setStyleSheet("gridline-color: rgb(0, 0, 0);")
        self.PhotoFrame.setText("")
        self.PhotoFrame.setObjectName("PhotoFrame")
        self.AddingPhoto = QtWidgets.QPushButton(self.centralwidget)
        self.AddingPhoto.setGeometry(QtCore.QRect(20, 150, 211, 51))
        self.AddingPhoto.setStyleSheet("font: 25 oblique 11pt \"Umpush\";\n"
"background-color: rgb(255, 255, 255);\n"
"font: 63 13pt \"URW Gothic\";")
        self.AddingPhoto.setObjectName("AddingPhoto")
        self.SaveButton = QtWidgets.QPushButton(self.centralwidget)
        self.SaveButton.setGeometry(QtCore.QRect(780, 670, 271, 51))
        self.SaveButton.setStyleSheet("font: 25 oblique 11pt \"Umpush\";\n"
"background-color: rgb(255, 255, 255);\n"
"font: 63 13pt \"URW Gothic\";")
        self.SaveButton.setObjectName("SaveButton")
        self.ExEntry = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.ExEntry.setGeometry(QtCore.QRect(760, 20, 461, 511))
        self.ExEntry.setStyleSheet("font: 63 13pt \"URW Bookman\";\n"
"background-color: rgb(255, 255, 255);")
        self.ExEntry.setObjectName("ExEntry")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1238, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.Exit = QtWidgets.QMenu(self.menubar)
        self.Exit.setObjectName("Exit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.Quit = QtWidgets.QAction(MainWindow)
        self.Quit.setObjectName("Quit")
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_2)
        self.menu.addAction(self.action_3)
        self.Exit.addAction(self.Quit)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.Exit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.HideButton.setText(_translate("MainWindow", "Сокрыть"))
        self.TextEntry.setPlaceholderText(_translate("MainWindow", "Введите текст"))
        self.ExtractButton.setText(_translate("MainWindow", "Извлечь"))
        self.AddingPhoto.setText(_translate("MainWindow", "Выбрать изображение"))
        self.SaveButton.setText(_translate("MainWindow", "Сохранить изображение как..."))
        self.ExEntry.setPlaceholderText(_translate("MainWindow", "Извлеченный текст"))
        self.menu.setTitle(_translate("MainWindow", "Инструменты"))
        self.Exit.setTitle(_translate("MainWindow", "Выход"))
        self.action.setText(_translate("MainWindow", "Сокрыть текст"))
        self.action_2.setText(_translate("MainWindow", "Извлечь текст"))
        self.action_3.setText(_translate("MainWindow", "Очистить поля"))
        self.Quit.setText(_translate("MainWindow", "Выход"))
